#!/bin/bash

# Create user “developer” with UID equal to the one that owns
# directory “workspace”.
#USER_ID=$(stat -c "%u" /home/developer/)
USER_ID=1000

echo "developer:x:${USER_ID}:${USER_ID}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd
echo "developer:x:${USER_ID}:" >> /etc/group
echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer
chmod 0440 /etc/sudoers.d/developer
chown root:root /usr/bin/sudo && chmod 4755 /usr/bin/sudo
PASS=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32};echo;)
echo "developer:klee" | chpasswd
mkdir -p /home/developer
chown -R developer:developer /home/developer

# Start SSH server.
/usr/sbin/sshd -D